"""Foundation layer: shared data structures, DB connectors, formatters, config.

Public types are re-exported here so callers can use ``from tabulaflow.core
import SQLSchema, ExecResult, Usage`` instead of reaching into submodules.
"""

from tabulaflow.core.types import (
    AssistantMessage,
    ColumnRef,
    ErrorInfo,
    ExecResult,
    ForeignKeySchema,
    GraphPropertySchema,
    GraphView,
    GraphViewEdge,
    GraphViewNode,
    NodeSchema,
    NumericOrNull,
    PredQuery,
    PropertyGraphSchema,
    RelationshipEndpoint,
    RelationshipSchema,
    SQLColumnSchema,
    SQLSchema,
    SQLTableSchema,
    SystemMessage,
    TableRef,
    ToolCall,
    ToolResponse,
    Trajectory,
    Usage,
    UserMessage,
)
from tabulaflow.core.outputs import (
    ArtifactDef,
    ChartArtifactDef,
    GraphArtifactDef,
    MapArtifactDef,
    TableArtifactDef,
)

__all__ = [
    "AssistantMessage",
    "ArtifactDef",
    "ChartArtifactDef",
    "ColumnRef",
    "ErrorInfo",
    "ExecResult",
    "ForeignKeySchema",
    "GraphPropertySchema",
    "GraphView",
    "GraphViewEdge",
    "GraphViewNode",
    "GraphArtifactDef",
    "MapArtifactDef",
    "NodeSchema",
    "NumericOrNull",
    "PredQuery",
    "PropertyGraphSchema",
    "RelationshipEndpoint",
    "RelationshipSchema",
    "SQLColumnSchema",
    "SQLSchema",
    "SQLTableSchema",
    "SystemMessage",
    "TableRef",
    "TableArtifactDef",
    "ToolCall",
    "ToolResponse",
    "Trajectory",
    "Usage",
    "UserMessage",
]
