changelog:
  exclude:
    labels:
      - documentation
      - dependencies
      - chore

  categories:
    - title: Features
      labels:
        - enhancement

    - title: Fixes
      labels:
        - bug

    - title: Other changes
      labels:
        - "*"
