"""Browser output-pane server and payload builders."""

from tabulaflow.app.pane.cards import build_query_data, render_graph_data, render_map_data, render_record_data
from tabulaflow.app.pane.charts import _add_line_hover, build_chart_data
from tabulaflow.app.pane.server import (
    DEFAULT_OUTPUT_PANE_HOST,
    DEFAULT_OUTPUT_PANE_PORT_END,
    DEFAULT_OUTPUT_PANE_PORT_START,
    DEFAULT_OUTPUT_PANE_PORTS,
    OutputPane,
    OutputPanePortError,
    _PANE_HTML,
)
from tabulaflow.app.pane.tables import TABLE_RENDER_MAX_ROWS, build_table_data
from tabulaflow.app.pane.types import (
    CARD_ID_PREFIX,
    VIEW_KINDS,
    CardData,
    ChartCardData,
    ChartData,
    ColumnDesc,
    ColumnRole,
    DatasetData,
    GraphCardData,
    GraphData,
    MapCardData,
    MapData,
    PaneCard,
    PaneSource,
    PaneTurn,
    QueryCardData,
    QueryData,
    TableCardData,
    TableData,
    ViewKind,
    card_payload,
    manual_card_turn,
    turn_payload,
)

__all__ = [
    "DEFAULT_OUTPUT_PANE_HOST",
    "DEFAULT_OUTPUT_PANE_PORT_END",
    "DEFAULT_OUTPUT_PANE_PORT_START",
    "DEFAULT_OUTPUT_PANE_PORTS",
    "OutputPane",
    "OutputPanePortError",
    "CARD_ID_PREFIX",
    "VIEW_KINDS",
    "CardData",
    "ChartCardData",
    "ChartData",
    "ColumnDesc",
    "ColumnRole",
    "DatasetData",
    "GraphCardData",
    "GraphData",
    "MapCardData",
    "MapData",
    "PaneCard",
    "PaneSource",
    "PaneTurn",
    "QueryCardData",
    "QueryData",
    "TABLE_RENDER_MAX_ROWS",
    "TableCardData",
    "TableData",
    "ViewKind",
    "_PANE_HTML",
    "_add_line_hover",
    "build_chart_data",
    "build_query_data",
    "build_table_data",
    "card_payload",
    "manual_card_turn",
    "render_graph_data",
    "render_map_data",
    "render_record_data",
    "turn_payload",
]
